### ISSUE TITLE
Why not use BottomNavigationView?

### ISSUE THREAD

**Issue by Jiezhi** [adib2149/BottomNavBar#1]
Android has already offered a widget called [**BottomNavigationView**](https://developer.android.com/reference/android/support/design/widget/BottomNavigationView.html) , which can also do the same things.

What's the advantage of this project?

**Comment by adib2149** [comment]
Well, **BottomNavigationView** also can technically do similar things, but they do not look the same like this.

If we use the official **BottomNavigationView**, all the menus are visible when we are using 3 menus. But when we move to 4 or 5 menus, they are automatically collided, and the text can only be seen after one clicks on it.

![1](https://cloud.githubusercontent.com/assets/6183958/25172503/1c1ad370-2513-11e7-9c43-bcb2b4557bf4.gif)

But what if we want to achieve different lloking Bottom Navigation view, like Quora or 9gag, where all the four (or five) submenus are visible with their corresponding icons and texts.

![2](https://cloud.githubusercontent.com/assets/6183958/25172577/4d92e1c2-2513-11e7-8744-e47262d4fcea.jpg)

![3](https://cloud.githubusercontent.com/assets/6183958/25172590/5263f4fc-2513-11e7-86eb-8abb64a5d480.png)

This is where this library will come in handy. This library helps create all visible menu with icons and texts in their BottomNavigationView. 

Let me know if this clears your confusion. I should add this info in the README though!!
