### ISSUE TITLE
No of tabs

### ISSUE THREAD

**Issue by mukeshsolanki** [adib2149/BottomNavBar#3]
Let's say I want only 3 or 5 tabs. in that case this library is completely useless

**Comment by riddhimanadib** [comment]
Yes, you are right on point.

This library was created so solve a very specific problem, which is clearly described in the README. 
> Easily add **four tabbed** bottom navigation bar in your activity.

If you need more than that, please go for the Android official Bottom Navigation View. It might be useless to you, but not for everyone out there, right? Thanks anyway.
